#ifdef ENGLISH
#ifdef UKRAINIAN
#define FILENAME_INI "ALFACADUA.INI"
#define FILENAME_NEW "ALFACADUA.$NI"
#define PATTERNS_INI "ВІЗЕРУНКИ.INI"
#elif SPANISH
#define FILENAME_INI "ALFACADES.INI"
#define FILENAME_NEW "ALFACADES.$NI"
#define PATTERNS_INI "PATRONES.INI"
#else
#define FILENAME_INI "ALFACAD.INI"
#define FILENAME_NEW "ALFACAD.$NI"
#define PATTERNS_INI "PATTERNS.INI"
#endif
#else 
#define FILENAME_INI "ALFACADPL.INI"
#define FILENAME_NEW "ALFACADPL.$NI"
#define PATTERNS_INI "WZORCE.INI"
#endif
#define CLOUD_INI "CLOUD.INI"